version: "3.3"
services:
  postgres:
    image: postgres
    container_name: "tasks-api"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
    external: true
